newproperty(:ensure) do
  include EasyType

  desc "is the crust baked or raw"


  newvalue(:baked) do
    provider.create
    nil # return nil so the event is autogenerated
  end

  newvalue(:absent) do
    provider.destroy
    nil # return nil so the event is autogenerated
  end

  defaultto do
    provider.managed? ? :raw : nil
  end

  to_translate_to_resource do | raw_resource|
    raw_resource.column_data('ensure').downcase.to_sym
  end
end
